### ISSUE TITLE
relight net

### ISSUE THREAD

**Issue by Zruto** [aasharma90/RetinexNet_PyTorch#3]
I want to know why the author uses R and I together as the input of the Relight Net. Isn’t the I component adjusted?Can I use the I as input?

**Comment by aasharma90** [comment]
Hi @Zruto 

Sorry for the late reply, but I believe the authors of the paper should be able to answer your question better than I can since it's their proposed method and my code here is only a re-implementation. Hence, closing this issue and hope your query gets resolved.
