### ISSUE TITLE
Train 

### ISSUE THREAD

**Issue by zuigezuixiaosa** [aasharma90/RetinexNet_PyTorch#4]
First, thank you for making the PyTorch model for RetinexNet!
I don't know why the image turns black after training，I hope I can get your guidance

**Comment by aasharma90** [comment]
Hi @zuigezuixiaosa 

For me to be able to help you, you would need to kindly provide more details about the observed "black" image and your training setup.  

Also, have you tried running the pretrained model provided in the repo first? Do you observe something similar or the results generated seem fine?

**Comment by zuigezuixiaosa** [comment]
Thank you very much. I changed a computer to try it yesterday and achieved preliminary results. We are investigating the cause now. I will contact you when I have further findings. Thank you very much

**Comment by aasharma90** [comment]
Hi @zuigezuixiaosa 

Hope you were able to resolve the issue, in case you have any further questions, feel free to revisit.
